// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://6t3qvwt2gbc7dak5xftdbnmu7q.appsync-api.us-east-1.amazonaws.com/graphql',
          region: 'us-east-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-kf6oylfnhvdjfl62gytx24o6sq'
        }
    }
};

export default config;